version: '3.7'

services:
  mariadb:
    image: mariadb:10.4.8-bionic
    restart: always 
    volumes: 
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    networks: 
      - nextcloud_net
  nextcloud: 
    build: ./build/
    depends_on: 
      - mariadb
    restart: always
    env_file: nextcloud.env
    volumes: 
      - type: volume
        source: nextcloud_data
        target: /var/www/html
    networks: 
      - traefik_net
      - web
      - nextcloud_net
    environment: 
      - MYSQL_HOST=mariadb
    labels: 
      - "traefik.docker.network=traefik_net"
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}routerHTTP.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}routerHTTP.rule=Host(`${TRAEFIK_SUBDOMAIN}`)"
      - "traefik.http.middlewares.route2https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.routers.${SERVICE_NAME}routerHTTP.middlewares=route2https"
      - "traefik.http.routers.${SERVICE_NAME}router0.middlewares=nextcloud_redirect"
      - "traefik.http.routers.${SERVICE_NAME}router0.rule=Host(`${TRAEFIK_SUBDOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}router0.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}router0.tls.certresolver=mytlschallenge"
      #- "traefik.http.services.${SERVICE_NAME}service.loadbalancer.server.port=8200"
  onlyoffice: 
    image: myonlyoffice:1.0.0
    # build: ./build/onlyoffice/
    restart: always
    stdin_open: true
    tty: true
    networks: 
      - nextcloud_net
      - web
      - traefik_net
    labels:
      - "traefik.docker.network=traefik_net"
      - "traefik.enable=true"
      - "traefik.http.routers.${ONLY_OFFICE_SERVICE_NAME}routerHTTP.entrypoints=web"
      - "traefik.http.routers.${ONLY_OFFICE_SERVICE_NAME}routerHTTP.rule=Host(`${ONLY_OFFICE_DOMAIN}`)"
      - "traefik.http.middlewares.route2https.redirectscheme.scheme=https"
      - "traefik.http.routers.${ONLY_OFFICE_SERVICE_NAME}routerHTTP.middlewares=route2https"
      - "traefik.http.routers.${ONLY_OFFICE_SERVICE_NAME}router0.rule=Host(`${ONLY_OFFICE_DOMAIN}`)"
      - "traefik.http.routers.${ONLY_OFFICE_SERVICE_NAME}router0.entrypoints=websecure"
      - "traefik.http.routers.${ONLY_OFFICE_SERVICE_NAME}router0.tls.certresolver=mytlschallenge"
      - "traefik.http.services.${ONLY_OFFICE_SERVICE_NAME}service.loadbalancer.server.port=80"


volumes: 
  mariadb_data: 
    driver: local
  nextcloud_data: 
    driver: local

    
networks:
  web:
    driver: bridge
    name: web
  traefik_net: 
    driver: bridge
    name: traefik_net
  nextcloud_net:
    internal: true


